fixed more lfrc

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -1,44 +1,27 @@
-set ratios 1:2:3
 # interpreter for shell commands
-set shell sh
-
-# set '-eu' options for shell commands
-# These options are used to have safer shell commands. Option '-e' is used to
-# exit on error and option '-u' is used to give error for unset variables.
-# Option '-f' disables pathname expansion which can be useful when $f, $fs, and
-# $fx variables contain names with '*' or '?' characters. However, this option
-# is used selectively within individual commands as it can be limiting at
-# times.
+set shell bash
 set shellopts '-eu'
-
-# set internal field separator (IFS) to "\n" for shell commands
-# This is useful to automatically split file names in $fs and $fx properly
-# since default file separator used in these variables (i.e. 'filesep' option)
-# is newline. You need to consider the values of these options and create your
-# commands accordingly.
 set ifs "\n"
-
-# leave some space at the top and the bottom of the screen
 set scrolloff 10
-set icons
-# Use the `dim` attribute instead of underline for the cursor in the preview pane
 set cursorpreviewfmt "\033[7;2m"
 
+set incsearch
+set smartcase
+set ignorecase
+set anchorfind
+set findlen 1
+set tabstop 4
+set info size
+set preview
+set dircounts
+
+setlocal ~/Downloads sortby "atime"
+setlocal ~/Downloads reverse
+
+set cursorpreviewfmt "\033[7;2m"
 set previewer '~/.config/lf/previewer'
-# set cleaner '~/.config/lf/cleaner'
-# use enter for shell commands
-map <enter> shell
-
-# show the result of execution of previous commands
-map ` !true
-
-# execute current file (must be executable)
-map x $$f
-map X !$f
-
-# dedicated keys for file opener actions
-map o &mimeopen $f
-map O $mimeopen --ask $f
+set cleaner '~/.config/lf/cleaner'
+set icons
 
 # define a custom 'open' command
 # This command is called when current file is not a directory. You may want to
@@ -51,21 +34,18 @@ cmd open &{{
     esac
 }}
 
-# mkdir command. See wiki if you want it to select created dir
-map a :push %mkdir<space>
 
-# define a custom 'rename' command without prompt for overwrite
-# cmd rename %[ -e $1 ] && printf "file exists" || mv $f $1
-# map r push :rename<space>
+cmd mkdir $mkdir -p "$(echo $* | tr ' ' '\ ')"
 
-# make sure trash folder exists
-# %mkdir -p ~/.trash
+# Create a directory with the selected items
+cmd new-folder-with-selection ${{
+  set -f
+  printf "Directory name: "
+  read newd
+  mkdir -- "$newd"
+  mv -- $fx "$newd"
+}}
 
-# move current file or selected files to trash folder
-# (also see 'man mv' for backup/overwrite options)
-cmd trash %set -f; mv $fx ~/.trash
-
-# define a custom 'delete' command
 cmd delete ${{
     set -f
     printf "$fx\n"
@@ -74,10 +54,18 @@ cmd delete ${{
     [ "$ans" = "y" ] && rmtrash -rf $fx
 }}
 
-# use '<delete>' key for either 'trash' or 'delete' command
-# map <delete> trash
-# extract the current file with the right command
-# (xkcd link: https://xkcd.com/1168/)
+cmd trash !{{
+  set -f
+  printf "\nItems to be trashed:\n$fx\n\nTrash? [y/N]"
+  read ans
+  if [[ $ans == "y" ]]; then
+    trash -F $fx && echo "Trash complete!"
+  elif [[ $ans == "n" ]]; then
+    echo "Canceled!"
+  else
+    echo "Failed! Use y to trash."
+  fi
+}}
 
 cmd extract ${{
     set -f
@@ -85,9 +73,11 @@ cmd extract ${{
         *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
         *.tar.gz|*.tgz) tar xzvf $f;;
         *.tar.xz|*.txz) tar xJvf $f;;
+        *.tar) tar xvf $f;;
         *.zip) unzip $f;;
         *.rar) unrar x $f;;
         *.7z) 7z x $f;;
+        *) echo "Unsupported format";;
     esac
 }}
 
@@ -109,19 +99,111 @@ cmd zip ${{
     rm -rf $1
 }} 
 
+cmd select-all :unselect; invert
+
+# Bulk rename on selected files or all the non-hidden files in the current directory if no selection
+cmd bulk-rename ${{
+  old="$(mktemp)"
+  new="$(mktemp)"
+  if [ -n "$fs" ]; then
+    fs="$(basename $fs)"
+  else
+    fs="$(ls)"
+  fi
+  printf '%s\n' "$fs" >"$old"
+  printf '%s\n' "$fs" >"$new"
+  $EDITOR "$new"
+  [ "$(wc -l < "$new")" -ne "$(wc -l < "$old")" ] && exit
+  paste "$old" "$new" | while IFS= read -r names; do
+    src="$(printf '%s' "$names" | cut -f1)"
+    dst="$(printf '%s' "$names" | cut -f2)"
+    if [ "$src" = "$dst" ] || [ -e "$dst" ]; then
+        continue
+    fi
+    mv -- "$src" "$dst"
+  done
+  rm -- "$old" "$new"
+  lf -remote "send $id unselect"
+}}
+
+# Copy the file names (including extension) of the selections separated by \n
+cmd copy-filename ${{
+  names="$(echo $fx | tr ' ' '\n' | xargs -I{} basename {})"
+  echo $names | tr ' ' '\n' | pbcopy
+}}
+
+# Copy the absolute paths of selections separated by \n
+cmd copy-absolute-path ${{
+  echo $fx | tr ' ' '\n' | pbcopy
+}}
+
+# Select the file or directory via fzf
+cmd fzf-select ${{
+  IFS=' '
+  exclude=$(cat $HOME/exclude | sed 's/^/--exclude /' | tr '\n' ' ')
+  select=$(fd --hidden --follow $exclude | fzf) || true
+  lf -remote "send $id select $select"
+}}
+
+# cd into the selected directory via fzf
+cmd fzf-cd ${{
+  IFS=' '
+  exclude=$(cat $HOME/exclude | sed 's/^/--exclude /' | tr '\n' ' ')
+  select=$(fd --type d --hidden --follow $exclude | fzf) || true
+  lf -remote "send $id cd $select"
+}}
+
+# zoxide
+cmd z %{{
+  result="$(zoxide query --exclude $PWD $@ | sed 's/\\/\\\\/g;s/"/\\"/g')"
+  lf -remote "send $id cd \"$result\""
+}}
+
+cmd zi ${{
+  result="$(zoxide query -i | sed 's/\\/\\\\/g;s/"/\\"/g')"
+  lf -remote "send $id cd \"$result\""
+}}
+#unbind defaults
+map e
+
+map <enter> shell
+map ` !true
+
+map H jump-prev
+map L jump-next
+map J push jjjj
+map K push kkkk
+
+map <tab> :toggle;down
+map yy copy
+map yn copy-filename
+map yP copy-absolute-path
+
+map U !printf "\n";du -csh *
+map <c-f> fzf-select
+map <c-j> fzf-cd
+
+# give a name and then make a directory
+map ad push :mkdir<space>
+map aa push <enter>touch<space>
+map A new-folder-with-selection
+
+map V push :!nvim<space>
+
 # all custom mappings
 map D delete
 
-map e
 map ee extract
-map ez zip
-
 map ec $$EDITOR "$f"
 map el $$EDITOR ~/.config/lf/lfrc
 map en $$EDITOR ~/.config/nvim
-
-map rr rename
-map r. rename
+map <space>c push :zip<space>
+map r
+map rr rename # at the very end
+map ra push A<c-a> # at the very beginning
+map rn push A<c-u> # rename the filename
+map re push A<c-f><c-k> # rename the extension
+map <c-r> bulk-rename
 
 # [g]o [.]config/[?]__
 map g.l cd ~/.config/lf
@@ -151,3 +233,14 @@ map grpp cd ~/rose/py/project
 map grn cd ~/rose/norg
 map grd cd ~/rose/dotReferences
 map grt cd ~/rose/tools
+
+#bunch of stuff idk
+# map x $$f
+# map X !$f
+
+cmap <tab> cmd-menu-complete
+cmap <backtab> cmd-menu-complete-back
+
+# dedicated keys for file opener actions
+map o &mimeopen $f
+map O $mimeopen --ask $f
